name: rebi_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1

  get: ^4.6.5
  get_storage: ^2.0.3
  logger: ^1.1.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  rebi_tools: ^0.0.3
  google_fonts: ^3.0.1
  url_launcher: ^6.1.4
  lazy_load_scrollview: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300